// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKGh4X1Xc4sr-wCC4_EAwALCT-kn6pHDo',
    appId: '1:217179754695:web:cdd7410560677e8e7eeee2',
    messagingSenderId: '217179754695',
    projectId: 'tap-recipe-48a74',
    authDomain: 'tap-recipe-48a74.firebaseapp.com',
    storageBucket: 'tap-recipe-48a74.appspot.com',
    measurementId: 'G-SEM7DBF8J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMQGHzCxNcKTvqe7yKQLBBNrIrp7KGSgY',
    appId: '1:217179754695:android:aa0b84da86657af57eeee2',
    messagingSenderId: '217179754695',
    projectId: 'tap-recipe-48a74',
    storageBucket: 'tap-recipe-48a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3ZGmm7MrARegL2ZcVeQd0fhht9LyT04',
    appId: '1:217179754695:ios:243a7a7a58bbdd987eeee2',
    messagingSenderId: '217179754695',
    projectId: 'tap-recipe-48a74',
    storageBucket: 'tap-recipe-48a74.appspot.com',
    iosClientId: '217179754695-batna2eod1anovtg02ej7okcrbm6uc7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapRecipe',
  );
}
